### PR TITLE
feat: delay hiding the overlay

### PR DESCRIPTION
**Pull request by chrismwendt**
Resolves https://github.com/sourcegraph/codeintellify/issues/48

### CODE REVIEW

**Review by olafurpg — COMMENTED** [review]
What is the best way to try this out with a local Sourcegraph instance? I'd love to give it a spin.

> delay hiding the overlay

There's been recent discussions about using the term "popover" instead of hover/overlay. Not sure if we want to change anything in this repo yet but just wanted to bring it up since the PR title uses the word "overlay". cc/ @jjinnii

**Comment by chrismwendt** [comment]
To try this locally:

- Check out this PR, then `yarn link`
- `yarn run watch`
- cd into sourcegraph/sourcegraph then `yarn link "@sourcegraph/codeintellify"`
- `sg start enterprise-codeintel`
- Hover over some tokens

**Review by olafurpg — APPROVED** [review]
Just tried this locally! LGTM 👍 We may want to increase the delay a bit more but lets collect more feedback first.

**Comment by jjinnii** [comment]
@olafurpg @chrismwendt Thanks for tagging me! Obviously, this PR is merged now but if there's something in our repo that says overlay or for future PR related to the popover, it would be great if we could label "code intel popover" for clarity!

**Pull request merged**
